### PR TITLE
Linux build fixes

### PR DESCRIPTION
**Pull request by bobsayshilol**
This doesn't get us all the way there, but the remaining parts are either hacks or require additional functionality from `delta-studio`.

Note that 908103b4a10c7a874d21418ecf5aa0844602a876 depends on a similar change in https://github.com/ange-yaghi/delta-studio so merging this would fail as-is unless that's been merged.

This hasn't been tested on Windows but it should Just Work.

This addresses #2.

Blocked on https://github.com/ange-yaghi/delta-studio/pull/34.

### CODE REVIEW

**Comment by alexmyczko** [comment]
Thank you for working on this! I've given it a try with:

```
git clone --recursive https://github.com/bobsayshilol/engine-sim.git
```

but I get something like:

```
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_math.h:266:5: error:‘__forceinline’ does not name a type
  266 |     __forceinline ysVector Magnitude(const ysVector &v) {
      |     ^~~~~~~~~~~~~
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_math.h:272:5: error:‘__forceinline’ does not name a type
  272 |     __forceinline ysVector Normalize(const ysVector &v) {
      |     ^~~~~~~~~~~~~
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_math.h:276:5: error:‘__forceinline’ does not name a type
  276 |     __forceinline ysVector Negate(const ysVector &v) {
      |     ^~~~~~~~~~~~~
In file included from /var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/yds_animation_action.cpp:3:
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_animation_target.h: In member function ‘void TransformTarget::ClearLocation(const ysVector&)’:
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_animation_target.h:33:27: error: ‘GetX’ is not a member of ‘ysMath’
   33 |         Data[0] = ysMath::GetX(t);
      |                           ^~~~
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_animation_target.h:34:27: error: ‘GetY’ is not a member of ‘ysMath’
   34 |         Data[1] = ysMath::GetY(t);
      |                           ^~~~
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_animation_target.h:35:27: error: ‘GetZ’ is not a member of ‘ysMath’
   35 |         Data[2] = ysMath::GetZ(t);
      |                           ^~~~
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_animation_target.h: In member function ‘void TransformTarget::AccumulateQuaternion(ysQuaternion&, float)’:
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_animation_target.h:64:38: error: ‘GetScalar’ is not a member of ‘ysMath’
   64 |             float cosTheta = ysMath::GetScalar(ysMath::Dot(current, q));
      |                                      ^~~~~~~~~
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_animation_target.h:64:56: error: ‘Dot’ is not a member of ‘ysMath’; did you mean ‘Dot3’?
   64 |             float cosTheta = ysMath::GetScalar(ysMath::Dot(current, q));
      |                                                        ^~~
      |                                                        Dot3
/var/www/debian/engine-sim/git2/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_animation_target.h:68:39: error: ‘Negate’ is not a member of ‘ysMath’; did you mean ‘Negate3’?
   68 |                 transformed = ysMath::Negate(q);
      |                                       ^~~~~~
      |                                       Negate3
gmake[2]: *** [dependencies/submodules/delta-studio/CMakeFiles/delta-core.dir/build.make:76: dependencies/submodules/delta-studio/CMakeFiles/delta-core.dir/src/yds_animation_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:581: dependencies/submodules/delta-studio/CMakeFiles/delta-core.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

**Comment by bobsayshilol** [comment]
Yeah, that's why it's still in draft. It requires changes to https://github.com/ange-yaghi/delta-studio too which is where you're seeing all of the errors. Check the discord for the current progress.

**Comment by alexmyczko** [comment]
I read about that "discort", but no clue what it is? URL?

**Comment by bobsayshilol** [comment]
> discord has never worked for me, can't join, invalid invite code, my account is not working, whatever. is there a matrix room, or irc channel for this?

I don't believe so. If it's not mentioned in the repo README or the youtube video then it's probably not a thing.

**Comment by MacSlash** [comment]
I'm trying to ask about adding an IRC / Matrix channel rn, I'll link the Matrix if it gets added

**Comment by MacSlash** [comment]
Okay well I was given permission to create my own Matrix channel to discuss it, at address #unofficial-engine-sim:matrix.org and I added an IRC Bridge with channel name #unofficial-engine-sim

**Comment by TheFGFSEagle** [comment]
So does this compile on Linux in way yet ? Seen your demo video on YouTube … you made an incredible program, really.

**Comment by bobsayshilol** [comment]
Replaced by #346 which is more feature complete.

**Pull request closed without merging**
